import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "./contexts/AuthContext";
import QueryProvider from "./contexts/QueryProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <QueryProvider>
          <body className={inter.className}>{children}</body>
        </QueryProvider>
      </AuthContextProvider>
    </html>
  );
}
